import { ToolBar, ToolButton } from "ToolBar.slint";
import { Show, Filter, FilterStatus } from "Structs.slint";
import { AddShowWindow } from "AddShowWindow.slint";
import { ShowWindow } from "ShowWindow.slint";
import { ChangePictureDialog } from "ChangePictureDialog.slint";
import { Images, Palette } from "Global.slint";
import { Watchlist } from "Watchlist.slint";
import { LoadingWindow } from "LoadingWidget.slint";

export struct ImageDetails {
    source: image,
    path: string,
}

export component AppWindow inherits Window {
    min-width: 800px;
    min-height: 600px;
    preferred-width: 1000px;
    preferred-height: 800px;
    title: "Watchlist";

    callback add-show([Show], Show);
    callback can-import-show-by-link(string) -> bool;
    callback cancel-show();
    callback check-new-episode-available(Show) -> bool;
    callback change-new-episodes-available-status(int, bool);
    callback episode-changed(Show);
    callback favorite-changed(Show);
    callback show-filter([Show], Filter) -> [Show];
    callback display-dropped();
    callback get-local-image-path() -> string;
    callback get-weekday-now() -> int;
    callback get-weekday(string) -> int;
    callback import-clicked(string) -> Show;
    callback load-image(string) -> ImageDetails;
    callback open-link(string);
    callback parse-datetime(string) -> [int];
    callback remove-show([Show], Show);
    callback score-changed(Show);
    callback search([Show], string) -> [Show];
    callback season-changed(Show);
    callback set-shows([Show]);
    callback status-changed(Show);

    property <ImageDetails> show-image;
    in-out property <[Show]> shows;
    property <Filter> filter;
    in-out property loading-progress <=> loadinw-window.progress;

    function load-image-impl(name: string) -> image {
        show-image = root.load-image(name);
        if (show-image.source.width == 0) {
            return Images.show-picture;
        }
        else {
            add-window.link-to-picture = show-image.path;
            return show-image.source;
        }
    }

    function use-filter() {
        watchlist.shows = show-filter(shows, filter);
    }

    function sync-shows-with(show: Show) {
        shows[show.index] = show;
        use-filter();
    }

    set-shows(s) => {
        shows = s;
        watchlist.shows = shows;
    }

    change-new-episodes-available-status(i, is-available) => {
        shows[i].new-episodes-available = is-available;
        use-filter();
    }

    watchlist := Watchlist {
        background: Palette.secondary;

        loadinw-window := LoadingWindow {
        }

        add-clicked => {
            self.visible = false;
            add-window.reset();
            add-window.visible = true;
        }

        show-clicked(show) => {
            self.visible = false;
            show-window.day-now = get-weekday-now();
            show-window.display-show(show);
            show-window.visible = true;
        }

        search(text) => {
            watchlist.shows = search(shows, text);
        }

        search-cancel => {
            use-filter();
        }

        display-watching => {
            filter.status = FilterStatus.watching;
            use-filter();
        }

        display-planned => {
            filter.status = FilterStatus.planned;
            use-filter();
        }

        display-completed => {
            filter.status = FilterStatus.completed;
            use-filter();
        }

        display-liked => {
            filter.status = FilterStatus.liked;
            use-filter();
        }

        display-dropped => {
            filter.status = FilterStatus.dropped;
            use-filter();
        }

        cancel-quick-filter => {
            filter.status = FilterStatus.all;
            use-filter();
        }
    }

    show-window := ShowWindow {
        background: Palette.secondary;
        visible: false;

        score-changed => {
            score-changed(self.show);
            sync-shows-with(self.show);
        }

        status-changed => {
            status-changed(self.show);
            sync-shows-with(self.show);
        }

        favorite-changed => {
            favorite-changed(self.show);
            sync-shows-with(self.show);
        }

        season-changed => {
            season-changed(self.show);
            sync-shows-with(self.show);
        }

        episode-changed => {
            episode-changed(self.show);
            self.show.new-episodes-available = check-new-episode-available(self.show);
            sync-shows-with(self.show);
        }

        back(is-changed, show) => {
            self.visible = false;
            watchlist.search-mode = false;
            watchlist.visible = true;
            if (is-changed) {
                sync-shows-with(self.show);
            }
        }

        edit(show) => {
            self.visible = false;
            add-window.set-show(show);
            add-window.visible = true;
        }

        remove(show) => {
            remove-show(shows, show);
            self.visible = false;
            watchlist.visible = true;
        }

        open-link(link) => {
            open-link(link);
        }
    }

    add-window := AddShowWindow {
        background: Palette.secondary;
        visible: false;

        add-show(show) => {
            root.add-show(shows, show);
            self.visible = false;
            watchlist.visible = true;
            use-filter();
        }

        cancel-show => {
            root.cancel-show();
            self.visible = false;
            watchlist.visible = true;
        }

        change-picture => {
            change-picture-dialog.show();
        }

        link-changed(link) => {
            return can-import-show-by-link(link);
        }

        import-clicked(link) => {
            return import-clicked(link);
        }

        load-image(name) => {
            return load-image-impl(name);
        }

        get-weekday(datetime) => {
            return get-weekday(datetime);
        }

        parse-datetime(datetime) => {
            return parse-datetime(datetime);
        }
    }

    change-picture-dialog := ChangePictureDialog {
        width: root.width;
        height: root.height;

        load-image(name) => {
            add-window.show-image = load-image-impl(name);
        }

        get-local-path() => {
            return get-local-image-path();
        }
    }
}

