import { ToolBar, ToolButton } from "ToolBar.slint";
import { Show } from "Structs.slint";
import { AddShowWindow } from "AddShowWindow.slint";
import { ShowWindow } from "ShowWindow.slint";
import { ChangePictureDialog } from "ChangePictureDialog.slint";
import { Images, Palette } from "Global.slint";
import { Watchlist } from "Watchlist.slint";

export struct ImageDetails {
    source: image,
    path: string,
}

export component AppWindow inherits Window {
    min-width: 800px;
    min-height: 600px;
    preferred-width: 1000px;
    preferred-height: 800px;
    title: "Watchlist";

    callback add-show(Show);
    callback can-import-show-by-link(string) -> bool;
    callback cancel-show();
    callback episode-changed(Show);
    callback favorite-changed(Show);
    callback get-local-image-path() -> string;
    callback get-weekday-now() -> int;
    callback get-weekday(string) -> int;
    callback import-clicked(string) -> Show;
    callback load-image(string) -> ImageDetails;
    callback open-link(string);
    callback parse-datetime(string) -> [int];
    callback remove-show(Show);
    callback score-changed(Show);
    callback search(string);
    callback season-changed(Show);
    callback status-changed(Show);
    callback update-watchlist();

    out property <ImageDetails> show-image;
    in property shows <=> watchlist.shows;

    function load-image-impl(name: string) -> image {
        show-image = root.load-image(name);
        if (show-image.source.width == 0) {
            return Images.show-picture;
        }
        else {
            add-window.link-to-picture = show-image.path;
            return show-image.source;
        }
    }

    watchlist := Watchlist {
        background: Palette.secondary;

        add-clicked => {
            self.visible = false;
            add-window.reset();
            add-window.visible = true;
        }

        show-clicked(show) => {
            self.visible = false;
            show-window.day-now = get-weekday-now();
            show-window.display-show(show);
            show-window.visible = true;
        }

        search(text) => {
            search(text);
        }

        search-cancel => {
            update-watchlist();
        }
    }

    show-window := ShowWindow {
        background: Palette.secondary;
        visible: false;

        score-changed => {
            score-changed(show-window.show);
        }

        status-changed => {
            status-changed(show-window.show);
        }

        favorite-changed => {
            favorite-changed(show-window.show);
        }

        season-changed => {
            season-changed(show-window.show);
        }

        episode-changed => {
            episode-changed(show-window.show);
        }

        back(is-changed) => {
            self.visible = false;
            watchlist.search-mode = false;
            watchlist.visible = true;
            if (is-changed) {
                update-watchlist();
            }
        }

        edit(show) => {
            self.visible = false;
            add-window.set-show(show);
            add-window.visible = true;
        }

        remove(show) => {
            remove-show(show);
            self.visible = false;
            watchlist.visible = true;
            update-watchlist();
        }

        open-link(link) => {
            open-link(link);
        }
    }

    add-window := AddShowWindow {
        background: Palette.secondary;
        visible: false;

        add-show(show) => {
            root.add-show(show);
            self.visible = false;
            watchlist.visible = true;
            update-watchlist();
        }

        cancel-show => {
            root.cancel-show();
            self.visible = false;
            watchlist.visible = true;
        }

        change-picture => {
            change-picture-dialog.show();
        }

        link-changed(link) => {
            return can-import-show-by-link(link);
        }

        import-clicked(link) => {
            return import-clicked(link);
        }

        load-image(name) => {
            return load-image-impl(name);
        }

        get-weekday(datetime) => {
            return get-weekday(datetime);
        }

        parse-datetime(datetime) => {
            return parse-datetime(datetime);
        }
    }

    change-picture-dialog := ChangePictureDialog {
        width: root.width;
        height: root.height;

        load-image(name) => {
            add-window.show-image = load-image-impl(name);
        }

        get-local-path() => {
            return get-local-image-path();
        }
    }
}

