import { Button, VerticalBox, HorizontalBox, LineEdit, StandardButton } from "std-widgets.slint";
import { Images, Palette } from "Global.slint";

export component ChangePictureDialog inherits Dialog {
    callback load-image(string);
    callback get-local-path() -> string;
    out property <image> image: Images.show-picture;

    padding: 0px;
    visible: false;

    public function show() {
        root.visible = true;
        address.focus();
    }

    Rectangle {
        background: rgba(12, 12, 12, 90%);

        TouchArea {}

        Rectangle {
            background: Palette.secondary;
            width: 470px;
            height: 140px;
            x: root.width * 1px / 2px - self.width * 1px / 2px;
            y: root.height * 1px / 2px - self.height * 1px / 2px;

            Rectangle {
                width: parent.width;
                height: 35px;
                y: 0;
                background: Palette.primary;
            }

            VerticalBox {
                alignment: start;

                Text {
                    text: @tr("Choose a picture for the show by https link or on the local disk");
                }

                HorizontalBox {
                    address := LineEdit {
                        placeholder-text: @tr("Path to the picture");

                        accepted => {
                            root.load-image(address.text);
                            root.visible = false;
                            address.text = "";
                        }
                    }

                    Button {
                        text: @tr("Open...");
                        clicked => {
                            address.text = get-local-path();
                        }
                    }
                }

                HorizontalBox {
                    alignment: end;

                    StandardButton {
                        kind: ok;

                        clicked => {
                            root.load-image(address.text);
                            root.visible = false;
                            address.text = "";
                        }
                    }

                    StandardButton {
                        kind: cancel;

                        clicked => {
                            root.visible = false;
                            address.text = "";
                        }
                    }
                }
            }
        }
    }
}


