export global Images {
    out property <image> watch-later: @image-url("assets/clock.png");
    out property <image> watching: @image-url("assets/view.png");
    out property <image> completed: @image-url("assets/check-mark.png");
    out property <image> liked: @image-url("assets/love.png");
    out property <image> dropped: @image-url("assets/dislike.png");
    out property <image> show-picture: @image-url("assets/picture.png");
    out property <image> star: @image-url("assets/star.png");
    out property <image> star-inactive: @image-url("assets/star2.png");
    out property <image> import: @image-url("assets/import.png");
    out property <image> heart: @image-url("assets/heart.png");
    out property <image> add: @image-url("assets/add.png");
    out property <image> edit: @image-url("assets/editing.png");
    out property <image> remove: @image-url("assets/trash.png");
    out property <image> remove_sure: @image-url("assets/trash_red.png");
    out property <image> cancel: @image-url("assets/close.png");
    out property <image> list: @image-url("assets/list.png");
    out property <image> list-compact: @image-url("assets/list_compact.png");
    out property <image> search: @image-url("assets/search.png");
    out property <image> up: @image-url("assets/up-arrow.png");
    out property <image> down: @image-url("assets/down-arrow.png");
    out property <image> left: @image-url("assets/left-arrow.png");
    out property <image> right: @image-url("assets/right-arrow.png");
    out property <[image]> stars: [
        @image-url("assets/stars/0.png"),
        @image-url("assets/stars/1.png"),
        @image-url("assets/stars/2.png"),
        @image-url("assets/stars/3.png"),
        @image-url("assets/stars/4.png"),
        @image-url("assets/stars/5.png"),
        @image-url("assets/stars/6.png"),
        @image-url("assets/stars/7.png"),
        @image-url("assets/stars/8.png"),
        @image-url("assets/stars/9.png"),
        @image-url("assets/stars/10.png"),
    ];
}

export global Palette {
    out property <color> primary: #232323;
    out property <color> secondary: #313131;
    out property <color> border: #555555;
    out property <color> text: #f0f0f0;
    out property <color> placeholder: #a0a0a0;

    out property <color> yellow: #a7a341;
    out property <color> green: #2d883b;
    out property <color> blue: #417ca6;
    out property <color> light-blue: #79C9FF;
    out property <color> purple: #a240ab;
    out property <color> red: #942e2e;
}

