export global Images {
    out property <image> show-picture: @image-url("assets/picture.png");
    out property <image> star: @image-url("assets/star.png");
    out property <image> star-inactive: @image-url("assets/star2.png");
    out property <image> import: @image-url("assets/import.png");
    out property <image> heart: @image-url("assets/heart.png");
    out property <image> add: @image-url("assets/add.png");
    out property <image> edit: @image-url("assets/editing.png");
    out property <image> remove: @image-url("assets/trash.png");
    out property <image> remove_sure: @image-url("assets/trash_red.png");
    out property <image> cancel: @image-url("assets/close.png");
    out property <image> list: @image-url("assets/list.png");
    out property <image> list-compact: @image-url("assets/list_compact.png");
    out property <[image]> stars: [
        @image-url("assets/stars/0.png"),
        @image-url("assets/stars/1.png"),
        @image-url("assets/stars/2.png"),
        @image-url("assets/stars/3.png"),
        @image-url("assets/stars/4.png"),
        @image-url("assets/stars/5.png"),
        @image-url("assets/stars/6.png"),
        @image-url("assets/stars/7.png"),
        @image-url("assets/stars/8.png"),
        @image-url("assets/stars/9.png"),
        @image-url("assets/stars/10.png"),
    ];
}

