import { Palette } from "Global.slint";

export component LineEdit inherits Rectangle {
    in property text <=> main-text.text;
    in property text-color <=> main-text.color;
    in property placeholder-text <=> placeholder.text;
    in property input-type <=> main-text.input-type;

    preferred-height: 30px;
    background: Palette.primary;
    border-color: Palette.border;
    border-width: 1px;
    clip: true;
    vertical-stretch: 0;

    callback edited();
    callback accepted();

    public function text-focus() {
        main-text.focus();
    }

    placeholder := TextInput {
        color: main-text.color.darker(70%);
        read-only: true;
        vertical-alignment: center;
        visible: main-text.text == "";
        x: 5px;
    }

    main-text := TextInput {
        color: white;
        vertical-alignment: center;
        x: 5px;

        edited => {
            root.edited();
        }

        accepted => {
            root.accepted();
        }
    }
}
