import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Show, Status } from "Show.slint";
import { Images } from "Global.slint";

export component ListElement inherits Rectangle {
    in property <Show> show;

    height: 150px;

    Rectangle {
        x: 0px;
        width: 8px;

        states [
            completed when show.status == Status.completed: {
                background: root.background;
            }
            watch-later when show.status == Status.watch-later: {
                background: #c2bd20;
            }
            watching when show.status == Status.watching: {
                background: #26a725;
            }
            dropped when show.status == Status.dropped: {
                background: #cb2d2d;
            }
        ]
    }

    HorizontalBox {
        padding: 10px;
        spacing: 10px;

        picture := Image {
            source: show.picture.width > 0 ? show.picture : Images.show-picture;
            width: 100px;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        VerticalBox {
            padding: 0px;
            spacing: 0px;

            Text {
                font-size: 20px;
                font-weight: 900;
                text: show.title;
            }

            Text {
                text: show.alternative-title;
            }

            Text {
                text: show.release-date;
            }

            HorizontalBox {
                padding: 0px;
                spacing: 5px;
                alignment: start;

                HorizontalBox {
                    padding: 0px;
                    spacing: 2px;

                    star := Image {
                        width: 32px;
                        height: 24px;
                        source: Images.stars[show.score];
                        visible: show.score != 0;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }
                }

                Image {
                    width: 24px;
                    height: 24px;
                    source: Images.heart;
                    visible: show.favorite;
                    vertical-alignment: center;
                }
            }
        }
    }
}
