import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Show, Status } from "Show.slint";
import { Images } from "Global.slint";

export component ListElement inherits Rectangle {
    in property <Show> show;
    in property title-color <=> title.color;

    height: 150px;

    HorizontalBox {
        padding: 0px;
        spacing: 10px;

        Rectangle {
            width: 8px;

            states [
                completed when show.status == Status.completed: {
                    background: root.background;
                }
                watch-later when show.status == Status.watch-later: {
                    background: #c2bd20;
                }
                watching when show.status == Status.watching: {
                    background: #26a725;
                }
                dropped when show.status == Status.dropped: {
                    background: #cb2d2d;
                }
            ]
        }

        picture := Image {
            source: show.picture.width > 0 ? show.picture : Images.show-picture;
            width: 100px;
            max-height: root.height - 1px;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        VerticalBox {
            padding: 0px;
            spacing: 0px;
            alignment: space-around;

            title := Text {
                font-size: 20px;
                font-weight: 900;
                text: show.title;
            }

            alternative := Text {
                text: show.alternative-title;
            }

            release := Text {
                text: show.release-date;
            }

            HorizontalBox {
                padding: 0px;
                spacing: 5px;
                alignment: start;

                HorizontalBox {
                    padding: 0px;
                    spacing: 2px;

                    star := Image {
                        width: 24px;
                        height: 24px;
                        source: Images.stars[show.score];
                        visible: show.score != 0;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }
                }

                favorite := Image {
                    width: 24px;
                    height: 24px;
                    source: Images.heart;
                    visible: show.favorite;
                    vertical-alignment: center;
                }
            }
        }
    }
}

export component ListElementCompact inherits Rectangle {
    in property <Show> show;
    in property title-color <=> title.color;

    height: 50px;

    HorizontalBox {
        padding: 0px;
        spacing: 10px;

        Rectangle {
            width: 8px;

            states [
                completed when show.status == Status.completed: {
                    background: root.background;
                }
                watch-later when show.status == Status.watch-later: {
                    background: #c2bd20;
                }
                watching when show.status == Status.watching: {
                    background: #26a725;
                }
                dropped when show.status == Status.dropped: {
                    background: #cb2d2d;
                }
            ]
        }

        picture := Image {
            source: show.picture.width > 0 ? show.picture : Images.show-picture;
            width: 35px;
            max-height: root.height - 1px;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        VerticalLayout {
            alignment: center;

            HorizontalBox {
                padding: 0px;
                spacing: 10px;

                title := Text {
                    font-size: 16px;
                    text: show.title;
                }

                favorite := Image {
                    width: 24px;
                    height: 24px;
                    source: Images.heart;
                    visible: show.favorite;
                    vertical-alignment: center;
                }

                star := Image {
                    width: 24px;
                    height: 24px;
                    source: Images.stars[show.score];
                    visible: show.score != 0;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                }

                Rectangle { width: 1px; }
            }
        }
    }
}
