export enum Status {
    watch-later,
    watching,
    completed,
    dropped,
}

export enum ShowType {
    serial,
    film,
    cartoon,
    anime,
}

export enum FilterShowType {
    all,
    serial,
    film,
    cartoon,
    anime,
}

export enum FilterStatus {
    all,
    watching,
    planned,
    completed,
    liked,
    dropped,
}

export enum FilterOngoing {
    all,
    ongoing,
    completed,
}

export struct Filter {
    status: FilterStatus,
    show-type: FilterShowType,
    ongoing: FilterOngoing,
    year: int,
}

export struct Show {
    id: int,
    title: string,
    alternative-title: string,
    release-date: string,
    about: string,
    link-to-show: string,
    score: int,
    favorite: bool,
    status: Status,
    link-to-picture: string,
    picture: image,
    show-type: ShowType,
    season: int,
    episodes_count: int,
    episode: int,
    release-time: string,
    schedule-monday: int,
    schedule-tuesday: int,
    schedule-wednesday: int,
    schedule-thursday: int,
    schedule-friday: int,
    schedule-saturday: int,
    schedule-sunday: int,
    new-episodes-available: bool,
}

