import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { ToolBar, ToolButton } from "ToolBar.slint";
import { Show, Status } from "Structs.slint";
import { Images, Palette } from "Global.slint";
import { TextEdit } from "TextEdit.slint";
import { LineEdit } from "LineEdit.slint";
import { ListElement, ListElementCompact } from "ListElement.slint";

export component Watchlist inherits Rectangle {
    in-out property <[Show]> shows;
    out property <bool> mode-compact: false;
    callback add-clicked();
    callback show-clicked(Show);
    callback search(string);
    callback search-cancel();
    callback cancel-quick-filter();
    callback display-watching();
    callback display-planned();
    callback display-completed();
    callback display-liked();
    callback display-dropped();
    callback list-changed();

    in-out property <bool> search-mode: false;

    list-changed => {
        list.viewport-y = 0;
        list-compact.viewport-y = 0;
    }

    VerticalLayout {
        alignment: start;

        search-toolbar := ToolBar {
            height: search-mode ? 50px : 0px;
            background: Palette.primary;
            visible: search-mode;

            HorizontalBox {
                padding: 0px;
                spacing: 0px;
                width: parent.width;
                height: parent.height;
                alignment: stretch;
                property <bool> is-changed;

                search-input := LineEdit {
                    placeholder-text: "Enter the show name here";
                    border-width: 0px;

                    edited => {
                        is-changed = true;
                        search(self.text);
                        list-changed();
                    }
                }

                cancel-button := ToolButton {
                    hint: "Cancel";
                    hint-direction-left: true;
                    icon: Images.cancel;
                    width: 50px;
                    height: 50px;
                    background-color: Palette.primary;

                    clicked => {
                        search-mode = false;
                        if (is-changed) {
                            is-changed = false;
                            search-input.text = "";
                            search-cancel();
                            list-changed();
                        }
                    }
                }
            }
        }

        ToolBar {
            height: search-mode ? 0px : 50px;
            background: Palette.primary;
            visible: !search-mode;

            HorizontalBox {
                padding: 0px;
                spacing: 0px;
                width: parent.width;
                height: parent.height;
                alignment: space-between;

                HorizontalLayout {
                    alignment: start;

                    mode-button := ToolButton {
                        hint: "Change view mode";
                        icon: mode-compact ? Images.list-compact : Images.list;
                        width: 50px;
                        height: 50px;
                        background-color: Palette.primary;
                        z: 30;

                        clicked => {
                            mode-compact = !mode-compact;
                            list-changed();
                        }
                    }

                    add-button := ToolButton {
                        hint: "Add show";
                        icon: Images.add;
                        width: 50px;
                        height: 50px;
                        background-color: Palette.primary;
                        z: 29;

                        clicked => {
                            add-clicked();
                        }
                    }
                }

                HorizontalLayout {
                    alignment: center;

                    watching-button := ToolButton {
                        hint: "Watching";
                        icon: Images.watching;
                        width: 50px;
                        height: 50px;
                        background-color: Palette.primary;
                        checked-color: Palette.green;
                        checkable: true;
                        z: 20;

                        clicked => {
                            planned-button.checked = false;
                            completed-button.checked = false;
                            liked-button.checked = false;
                            dropped-button.checked = false;

                            if (self.checked) {
                                cancel-quick-filter();
                            }
                            else {
                                display-watching();
                            }
                            list-changed();
                        }
                    }

                    planned-button := ToolButton {
                        hint: "Planned";
                        icon: Images.watch-later;
                        width: 50px;
                        height: 50px;
                        background-color: Palette.primary;
                        checked-color: Palette.yellow;
                        checkable: true;
                        z: 19;

                        clicked => {
                            watching-button.checked = false;
                            completed-button.checked = false;
                            liked-button.checked = false;
                            dropped-button.checked = false;

                            if (self.checked) {
                                cancel-quick-filter();
                            }
                            else {
                                display-planned();
                            }
                            list-changed();
                        }
                    }

                    completed-button := ToolButton {
                        hint: "Completed";
                        icon: Images.completed;
                        width: 50px;
                        height: 50px;
                        background-color: Palette.primary;
                        checked-color: Palette.blue;
                        checkable: true;
                        z: 18;

                        clicked => {
                            watching-button.checked = false;
                            planned-button.checked = false;
                            liked-button.checked = false;
                            dropped-button.checked = false;

                            if (self.checked) {
                                cancel-quick-filter();
                            }
                            else {
                                display-completed();
                            }
                            list-changed();
                        }
                    }

                    liked-button := ToolButton {
                        hint: "Favorites";
                        icon: Images.liked;
                        width: 50px;
                        height: 50px;
                        background-color: Palette.primary;
                        checked-color: Palette.purple;
                        checkable: true;
                        z: 17;

                        clicked => {
                            watching-button.checked = false;
                            planned-button.checked = false;
                            completed-button.checked = false;
                            dropped-button.checked = false;

                            if (self.checked) {
                                cancel-quick-filter();
                            }
                            else {
                                display-liked();
                            }
                            list-changed();
                        }
                    }

                    dropped-button := ToolButton {
                        hint: "Dropped";
                        icon: Images.dropped;
                        width: 50px;
                        height: 50px;
                        background-color: Palette.primary;
                        checked-color: Palette.red;
                        checkable: true;
                        z: 16;

                        clicked => {
                            watching-button.checked = false;
                            planned-button.checked = false;
                            completed-button.checked = false;
                            liked-button.checked = false;

                            if (self.checked) {
                                cancel-quick-filter();
                            }
                            else {
                                display-dropped();
                            }
                            list-changed();
                        }
                    }
                }

                HorizontalLayout {
                    alignment: end;

                    // TODO:
                    filters-button := ToolButton {
                        // hint: "Filters";
                        // hint-direction-left: true;
                        // icon: Images.search;
                        width: 50px;
                        height: 50px;
                        // background-color: Palette.primary;
                        z: 2;

                        clicked => {
                        }
                    }

                    search-button := ToolButton {
                        hint: "Search";
                        hint-direction-left: true;
                        icon: Images.search;
                        width: 50px;
                        height: 50px;
                        background-color: Palette.primary;
                        z: 1;

                        clicked => {
                            search-mode = true;
                            search-input.text-focus();
                        }
                    }
                }
            }
        }

        /*if !root.mode-compact :*/ HorizontalLayout {
            property <float> scroll-coef: list.height / list.viewport-height;
            visible: !root.mode-compact;
            height: root.mode-compact ? 0px : root.height - 50px;

            list := Flickable {
                VerticalBox {
                    padding: 0px;
                    spacing: 0px;

                    for s[i] in shows : ListElement {
                        show: s;
                        title-color: s.new-episodes-available && s.status == Status.watching ?
                            Palette.light-blue : Palette.text;

                        Rectangle {
                            background: #101010;
                            height: 1px;
                            y: parent.height - 1px;
                        }

                        TouchArea {
                            clicked() => {
                                show-clicked(s);
                            }
                        }
                    }
                }
            }

            scrollbar := Rectangle {
                width: 8px;
                background: Palette.primary;

                scrollbar-indicator := Rectangle {
                    height: min(list.height, scroll-coef * list.height);
                    y: -list.viewport-y * scroll-coef;
                    background: Palette.border;
                }
            }
        }
        /*if root.mode-compact :*/ HorizontalLayout {
            property <float> scroll-coef: list-compact.height / list-compact.viewport-height;
            visible: root.mode-compact;
            height: root.mode-compact ? root.height - 50px : 0px;

            list-compact := Flickable {
                VerticalBox {
                    padding: 0px;
                    spacing: 0px;

                    for s[i] in shows : ListElementCompact {
                        show: s;
                        title-color: s.new-episodes-available && s.status == Status.watching ?
                            Palette.light-blue : Palette.text;

                        Rectangle {
                            background: #101010;
                            height: 1px;
                            y: parent.height - 1px;
                        }

                        TouchArea {
                            clicked() => {
                                show-clicked(s);
                            }
                        }
                    }
                }
            }

            scrollbar-compact := Rectangle {
                width: 8px;
                background: Palette.primary;

                scrollbar-indicator-compact := Rectangle {
                    height: min(list-compact.height, scroll-coef * list-compact.height);
                    y: -list-compact.viewport-y * scroll-coef;
                    background: Palette.border;
                }
            }
        }
    }
}
